apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: workshop
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: workshop
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to UpscaleConf 2025 - WaveSpeed Workshop</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 40px;
          line-height: 1.6;
        }
        h1 {
          color: #0066cc;
        }
        .container {
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
          border: 1px solid #ddd;
          border-radius: 5px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>UpscaleConf 2025 - WaveSpeed Workshop</h1>
        <p>Congratulations! You've successfully deployed the nginx service in your k3d cluster.</p>
        <p>This is the starting point for your workshop on managing high-volume requests at scale.</p>
        <p>Next steps:</p>
        <ul>
          <li>Deploy your application components</li>
          <li>Configure scaling rules</li>
          <li>Run load tests</li>
          <li>Monitor performance</li>
        </ul>
      </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: workshop
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: workshop
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80 